# Generated by Django 4.1 on 2022-08-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
        migrations.AddField(
            model_name='profile',
            name='chest_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='ОГ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_calorie_intake',
            field=models.IntegerField(blank=True, null=True, verbose_name='Суточная норма ккал'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_step_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Суточная норма шагов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_water_intake',
            field=models.FloatField(blank=True, null=True, verbose_name='Суточная норма воды, мл'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hip_circumference',
            field=models.IntegerField(blank=True, null=True, verbose_name='ОБ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_after',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото после'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_before',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото до'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_chest_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цель ОГ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_hip_circumference',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цель ОБ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_waist_circumference',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цель ОТ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цель по весу'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist_circumference',
            field=models.IntegerField(blank=True, null=True, verbose_name='ОТ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
