# Generated by Django 4.1 on 2022-08-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo_after_alter_profile_photo_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_after',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото после'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_before',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото до'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
    ]
