# Generated by Django 4.1 on 2022-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_photo_after_alter_profile_photo_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
