# Generated by Django 4.1 on 2022-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fitnessuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
