# Generated by Django 4.1 on 2022-08-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_courseday_tip_of_the_day'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdaydiary',
            name='course_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dairy', to='courses.courseday', verbose_name='День курса'),
        ),
        migrations.AlterField(
            model_name='classdaydiary',
            name='water',
            field=models.PositiveIntegerField(default=0, verbose_name='Вода в мл'),
        ),
        migrations.AlterUniqueTogether(
            name='classdaydiary',
            unique_together={('user', 'course_day')},
        ),
    ]
