# Generated by Django 4.1 on 2022-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursedaytaskuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseday',
            name='tip_of_the_day',
            field=models.TextField(blank=True, null=True, verbose_name='Совет дня'),
        ),
    ]
