# Generated by Django 4.1 on 2022-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseday_tip_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseday',
            name='number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Номер дня'),
        ),
    ]
