# Generated by Django 4.1 on 2022-08-17 16:43

from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to=food.models._image_path, verbose_name='Изображение')),
                ('recipe_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], default='breakfast', max_length=20, verbose_name='Тип')),
                ('satisfying', models.BooleanField(default=False, verbose_name='Сытный')),
                ('sweet', models.BooleanField(default=False, verbose_name='Сладкий')),
                ('simple', models.BooleanField(default=False, verbose_name='Простой')),
                ('exquisite', models.BooleanField(default=False, verbose_name='Изысканный')),
                ('speed', models.CharField(choices=[('quickly', 'Быстро'), ('slowly', 'Без спешки')], default='quickly', max_length=20, verbose_name='Скорость')),
                ('cooking_method', models.TextField(verbose_name='Способ приготовления')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления в минутах')),
                ('calories', models.PositiveIntegerField(verbose_name='Калории')),
                ('protein', models.PositiveIntegerField(verbose_name='Белок')),
                ('fats', models.PositiveIntegerField(verbose_name='Жиры')),
                ('carbohydrates', models.PositiveIntegerField(verbose_name='Углеводы')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food.recipe')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(through='food.RecipeProduct', to='food.product'),
        ),
    ]
