# Generated by Django 4.1 on 2022-08-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
    ]
