# Generated by Django 4.1 on 2022-08-23 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_courseday_tip_of_the_day'),
        ('food', '0004_alter_favorite_recipe_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=20, null=True, verbose_name='Тип')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Калории')),
                ('protein', models.PositiveIntegerField(default=0, verbose_name='Белок')),
                ('fats', models.PositiveIntegerField(default=0, verbose_name='Жиры')),
                ('carbohydrates', models.PositiveIntegerField(default=0, verbose_name='Углеводы')),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseday')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_intake', to='food.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_intake', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
            },
        ),
    ]
