# Generated by Django 4.1 on 2022-09-01 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseday_tip_of_the_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_foodintake'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodintake',
            unique_together={('user', 'recipe_type', 'course_day', 'recipe')},
        ),
    ]
