# Generated by Django 4.1 on 2022-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='calories_rating',
            field=models.PositiveIntegerField(default=5, help_text='от 0 до 5', verbose_name='Оценка по калориям'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_time',
            field=models.PositiveIntegerField(default=60, verbose_name='Время тренировки в минутах'),
        ),
    ]
