# Generated by Django 4.1 on 2022-09-03 05:30

from django.db import migrations, models
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_calories_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.FileField(blank=True, null=True, upload_to=training.models._video_path, verbose_name='Видео')),
                ('image', models.FileField(upload_to=training.models._image_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
    ]
